# Generated by Django 3.1.7 on 2021-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20210326_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='current_song',
        ),
    ]
